<header>     
   <h1 class='w3-theme-l3 heading-h1'><?php echo post('name');?></h1>
   <h3 class='w3-theme-l4 w3-center heading-h2'><?php echo presonal('b','lang')." : ".post('address');?></h3>
   <img class='w3-circle' style='position:absolute;top:4px;<?php echo post('lang') == 'ar'? 'right:5px;':'left:5px;right:0px;'; ?>' src="<?php echo $_SESSION['image']; ?>" width='100' height='100'>
   <h4 style='font-weight:bolder;font-style:italic;' class='w3-theme-l5 w3-center'><?php echo presonal('c','lang')." : ".rep(post('mobile'));?> - <?php echo  presonal('em','lang')." : ".post('email');?></h4>
</header>
  <h2 class='w3-badge w3-padding w3-theme-d1 heading-form'><?php echo heading('a','lang'); ?></h2>
  <p class='phar'><?php echo post('objective'); ?></p>
  <h2 class='w3-badge w3-padding w3-theme-d1 heading-form'><?php echo heading('b','lang'); ?></h2>   
  <ul class='phar' style='list-style:square'>
    <?php echo tags('<li><b>','</b></li>',[ 
         presonal('e','lang')." : ".rep(post('birthday')),
         presonal('d','lang')." : ".rep(post('religion')),
         presonal('g','lang')." : ".rep(post('gender')),
         presonal('h','lang')." : ".rep(post('status')),
         presonal('p','lang')." : ".rep(post('military')), 
    ]); ?>
  </ul>  
   <?php if (count($_SESSION['post']['edua']) > 0): ?>
   <h2 class='w3-badge w3-padding w3-theme-d1 heading-form'><?php echo heading('c','lang'); ?></h2>  
  <table class='w3-row'>
      <?php  
        echo maketag($_SESSION['post']['edua'],[
            'edua' => ['<tr><td width="40%"><h4 class="w3-text-theme">' => '</h4></td>'],
            'edub' => ['<td><b>' => "</b> - "],
            'educ' => ['<b>' => "</b></td></tr>"],
            'edud' => post('lang') == 'ar' ? ['<tr><td><b>الدرجة من : ' => "</b></td></tr>"]: ['<tr><td><b>dgree : ' => "</b></td></tr>"],
            'eduf' => ['<tr><td><b>' => '<b></td></tr>']
           ],['datemonth']); ?>
    </table>
   <?php endif; ?>
   <?php if (count($_SESSION['post']['worka']) > 0): ?>
    <br>  <br>
    <h2 class='w3-badge w3-padding w3-theme-d1 heading-form'><?php echo heading('d','lang'); ?></h2>  
  <table class='w3-row'>
    <?php  
      echo maketag($_SESSION['post']['worka'],[
          'worka' => ['<tr><td width="40%"><h4 class="w3-text-theme">' => '</h4></td>'],
          'workb' => ['<td><b>' => "</b> - "],
          'workc' => ['<b>' => "</b><td></tr>"],
          'workf' => ['<td><b>' => '<b></td></tr>'],
          'workd' => ['<td><b>' => '<b></td></tr>']
       ],['datemonth']); ?>
  </table>
  <?php endif; ?>
   <?php if (count($_SESSION['post']['skilla']) > 0): ?>
  <h2 class='w3-badge w3-padding w3-theme-d1 heading-form'><?php echo heading('h','lang'); ?></h2> 
  <table class='w3-row'><tr>
   <?php  
      echo maketag($_SESSION['post']['skilla'],[
          'skilla' => ['<td width="20%"><h4 class="w3-text-theme">' => '</h4></td>'],
          'skillb' => ['<td><b>' => '<b><td>']
     ],['rep']); 
   ?></tr>
  </table> 
 <?php endif ?>
 <?php if (count($_SESSION['post']['coursea']) > 0): ?>
    <h2 class='w3-badge w3-padding w3-theme-d1 heading-form'><?php echo heading('g','lang'); ?></h2>  
     <table class='w3-row'>
     <?php  
        echo maketag($_SESSION['post']['coursea'],[
            'coursea' => ['<tr><td width="40%"><h4 class="w3-text-theme">' => '</h4></td>'],
            'courseb' => ['<td><b>' => "</b> - "],
            'coursec' => ['<b>' => "</b></td></tr>"],
            'coursed' => ['<tr><td><b>' => '<b></td></tr>'],
            'coursef' => ['<tr><td><b>' => '<b></td></tr>']
           ],['datemonth']); ?>
    </table>
  <?php endif ?>
  <?php if (post('Intersets')): ?>
     <h2 class='w3-badge w3-padding w3-theme-d1 heading-form'><?php echo heading('p','lang'); ?></h2>
      <p class='phar'><?php echo post('Intersets'); ?></p>
  <?php endif ?>

