<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" type="text/css" href="<?php echo assets; ?>/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="<?php echo assets; ?>/css/style.css">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="<?php echo assets; ?>/js/html5shiv.min.js"></script>
    <script src="<?php echo assets; ?>/js/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/home/index">Help Services</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li <?php echo App::url(1) == 'home'?'class="active"':null ?>><a href="/home/index">Home</a></li>
            <li <?php echo App::url(1) == 'cv'?'class="active"':null ?>><a href="/cv/index">Cv</a></li>
          </ul>
          </div><!--/.nav-collapse -->
        </div>
      </nav>
      <div class="container">
        <?php echo $content; ?>
        </div><!-- /.container -->
        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="<?php echo assets; ?>/js/jquery.min.js"></script>
        <script src="<?php echo assets; ?>/js/bootstrap.min.js"></script>
        <script src="<?php echo assets; ?>/js/app.js"></script>
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script type="text/javascript" src='<?php echo assets.'/js/tinymce/tinymce.min.js';?>'></script>
        <script type="text/javascript">
          tinymce.init({
            selector: '.tinymcstextarea',
             height: 100,
              theme: 'modern',
              plugins: 'print preview fullpage searchreplace autolink directionality visualblocks visualchars fullscreen image link media template codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists textcolor wordcount imagetools contextmenu colorpicker textpattern help',
              toolbar1: 'formatselect | bold italic strikethrough forecolor backcolor | link | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent  | removeformat',
              image_advtab: true
          });
        </script>
      </body>
    </html>